language: php
php:
- '7.4'
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache"
install: composer install
stages:
- analyzing
- testing
jobs:
  include:
  - stage: testing
    name: Testing with CodeCeption
    env:
    - DB_CONFSTRING='mysql:host=127.0.0.1;dbname=cd_2020_db;charset=utf8'
    - DB_UNAME='root'
    - DB_PASSWD=''
    services:
    - mysql
    before_script:
    - php -S 127.0.0.1:8000 -t $TRAVIS_BUILD_DIR >/dev/null 2>&1 &
    - mysql -u root < doc/sql_dump.sql
    script:
    - php vendor/bin/codecept run
  - stage: build
    name: Heroku build
    if: branch = master
    script:
        deploy:
            provider: heroku
            api_key:
                secure: "TMiZdOy8gZFeWHZVqz2ltVnDqHgTqx440WEh7Jr8/t1juMsr936G9It3USshkrWm2J606AqlzcwF4wptN019ewgJOOdvAtdsdzRHlZ0pN2L0XEv9wuTHcux5L9NlFU83lTRjL8CYFrWVoT4nGW7+C9SUy675b+5IcSALfUwwwp4vde5syN2oSz3v9/ikZVobHIBLRd8X8H6FPcYr/ili3q6fkEcVgxQVm+z3f9lgBZ1xZkUvCr+3yVYAA5uwURZlC2JkX9Gv0mmzrxS6xKdz1i/nlTl75VMDMp3NfVf+mKggDXzjGcTNgeYTZbCZy6N+56xkkwg2RzY1dKiqHVs3JpCeQU3ykN4GRo0LxgI4V6XQIVSits//XOqAb2jZ9S2FzTOA4h+oSssefW4b7WeXs0Vtt4Z/hcaDqeacS03lTrm+DxJUz+DWGaW5BNq6628tiJicWmXz3CH8bCgm7Dr30lFdAo54/uk1l7KnHqNlPI7r06MuHzpQXWc7xFDxKFKzO96fPQbGbT3BPYPjNNbVW5TdmH6A4mDqAkaotNhw5jAxRTsKEILZ1nwqeGFkZJ9OXxgvihzo0TEJkcZwKxX4k7TWU6++4vf8UnZoy1w7MYySt8sry6NQKe73sT6mStAX+3rCax/d3/LZqrxccUsUpSeXmvJxkO9GEIGxKJQkqCQ="
            app: desolate-lake-59822
            on:
                repo: semperfidelis17/cd2020_project
