language: php
php:
- '7.4'
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache"
install: composer install
stages:
- analyzing
- testing
jobs:
  include:
  - stage: testing
    name: Testing with CodeCeption
    env:
    - DB_CONFSTRING='mysql:host=127.0.0.1;dbname=cd_2020_db;charset=utf8'
    - DB_UNAME='root'
    - DB_PASSWD=''
    services:
    - mysql
    before_script:
    - php -S 127.0.0.1:8000 -t $TRAVIS_BUILD_DIR >/dev/null 2>&1 &
    - mysql -u root < doc/sql_dump.sql
    script:
    - php assets/bin/codecept run
  
